// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh-zZZN9dHaNX2i31q9pmK8tsmmeH1q4s',
    appId: '1:558387951881:web:ad8780ded0c7d912bf7bd8',
    messagingSenderId: '558387951881',
    projectId: 'bedtime-writer-dev',
    authDomain: 'bedtime-writer-dev.firebaseapp.com',
    storageBucket: 'bedtime-writer-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwvvUcaNlVj57D2M1QVDKDhf8giJ3aEHA',
    appId: '1:558387951881:android:1d1075d740a89757bf7bd8',
    messagingSenderId: '558387951881',
    projectId: 'bedtime-writer-dev',
    storageBucket: 'bedtime-writer-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzvAYcUj7PbF1Ykyh6Gu-unlFB954qum4',
    appId: '1:558387951881:ios:778567a952333f34bf7bd8',
    messagingSenderId: '558387951881',
    projectId: 'bedtime-writer-dev',
    storageBucket: 'bedtime-writer-dev.appspot.com',
    androidClientId: '558387951881-5l5ppb1bv6m5167okecfkssfi9el38if.apps.googleusercontent.com',
    iosClientId: '558387951881-ln3evg34370bsll49f0touv7jsoja5pl.apps.googleusercontent.com',
    iosBundleId: 'com.dreamstorestudios.bedtimewriter.dev',
  );
}
