// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaub_nEmk3ivrPfVCDyLwT3VeOnQ6LTZY',
    appId: '1:856886395260:web:aa1bc8da139b87d677a4f9',
    messagingSenderId: '856886395260',
    projectId: 'bedtime-writer-prod',
    authDomain: 'bedtime-writer-prod.firebaseapp.com',
    storageBucket: 'bedtime-writer-prod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsBlhrMSLG8_2QGKbG7lSGyix3EAnqHTI',
    appId: '1:856886395260:android:0878692e71ce938677a4f9',
    messagingSenderId: '856886395260',
    projectId: 'bedtime-writer-prod',
    storageBucket: 'bedtime-writer-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Hcp4MhNtOjynrtDP4XMnmMBTW9qn7rM',
    appId: '1:856886395260:ios:563e9d9c302b1ec077a4f9',
    messagingSenderId: '856886395260',
    projectId: 'bedtime-writer-prod',
    storageBucket: 'bedtime-writer-prod.appspot.com',
    androidClientId: '856886395260-h58le8gjk6j42enfanj0sf6a2qnp3mlc.apps.googleusercontent.com',
    iosClientId: '856886395260-ra4mo2posth7ka056nv3ubnrstuv5mpo.apps.googleusercontent.com',
    iosBundleId: 'com.tap.bedtimewriter',
  );
}
