name: Frontend build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: read-all

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ "apk --debug", web ]
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env
        run: |
          touch .env

      - name: Install packages
        run: flutter pub get

      - name: Build
        run: flutter build ${{ matrix.target }}
