name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: read-all

jobs:
  ci:
    name: CI on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env
        run: |
          touch .env

      - name: Install packages
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

      - name: Dart format
        run: dart format --set-exit-if-changed --output none .

      - name: Run unit tests
        run: flutter test
