name: Frontend build

on:
  push:
    branches:
      - main
      - prod
  pull_request:
    branches:
      - main
      - prod

permissions: read-all

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ 'apk', 'web' ]
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          flutter-version: '3.10.6'

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env
        run: |
          touch .env

      - name: Install packages
        run: flutter pub get

      # Disabled because takes too much time.
      # - name: Build APK (dev)
      #  if: matrix.target == 'apk' && github.base_ref == 'main'
      #  run: flutter build apk --flavor dev

      - name: Build APK (prod)
        if: matrix.target == 'apk' && startsWith(github.base_ref, 'prod')
        run: flutter build apk --flavor prod

      - name: Build web
        if: matrix.target == 'web'
        run: flutter build web
